//both success & error messages
export var message = {
    msg1: "records found.",
    msg2: "Name is required.",
    msg3: "Email already exists.",
    msg4: "Email or password does not match.",
    msg5: "Logout successful.",
    msg6: "Registration successful.",
    msg7: "Unauthorized. Please Signout and Signin again.",
    msg8: "Please enter a valid email.",
    msg9: "Email is required.",
    msg10: "Password is required.",
    msg11: "Password is too short. Password must be atleast 8 characters.",
    msg12: "Password does not mtach.",
    msg13: "Register method required.",
    msg14: "Please accept the Terms & Conditions.",
    msg15: "Signin successful.",
    msg16: "Please enter the OTP.",
    msg17: "Email verified successfully.",
    msg18: "Email verification failed.",
    msg19: "OTP sent to your email address.",
    msg20: "Something went wrong.",
    msg21: "Profile updated successfully.",
    msg22: "Profile not updated successfully.",
    msg23: "Old password is required.",
    msg24: "New password is required.",
    msg25: "OTP does not match.",
    msg26: "records not found.",
    msg27: "Email does not exist.",
    msg28: "Signed up using Goolge. Use Google signin.",
    msg29: "Both passwords are the same. Please enter a new password.",
    msg30: "Password changed successfully.",
    msg31: "OTP matched.",
    msg32: "Signed up using Goolge. Use Google signin.",
    msg33: "Signed up using email. Use email signin.",
    msg34: "Language deleted.",
    msg35: "Language not deleted. Please try again.",
}